gui:
  # Disable auto-showing changed files in a tree format
  showFileTree: false
  # Nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  nerdFontsVersion: "3"
git:
  paging:
    # More readable diffs using git-delta
    pager: delta --dark --paging=never
